version: '3.8'

services:
  newsletter-api:
    build: .
    ports:
      - "8001:8001"
    env_file: .env
    depends_on:
      - newsletter-db
      - redis

  newsletter-worker:
    build: .
    command: celery -A app.worker.celery_app worker --loglevel=info
    env_file: .env
    depends_on:
      - newsletter-db
      - redis

  newsletter-db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: newsletter_db
    ports:
      - "5433:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6380:6379"
